<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AssemblyName>RevolutionaryStuff.BlazorWasm</AssemblyName>
        <PackageId>RevolutionaryStuff.BlazorWasm</PackageId>
        <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
        <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>This is a .NET 10 library</PackageReleaseNotes>
        <Authors>jason@jasonthomas.com</Authors>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseUrl>
        </PackageLicenseUrl>
        <PackageProjectUrl>https://github.com/jbt00000/RevolutionaryStuff</PackageProjectUrl>
        <RepositoryType>GIT</RepositoryType>
        <RepositoryUrl>https://github.com/jbt00000/RevolutionaryStuff.git</RepositoryUrl>
        <PackageIcon>package\icon.png</PackageIcon>
        <PackageLicenseFile>package\license.txt</PackageLicenseFile>
        <Copyright>Copyright © 2023</Copyright>
        <FileVersion>4.192.100</FileVersion>
        <AssemblyVersion>4.192.100</AssemblyVersion>
        <Version>4.192.100</Version>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Include="appsettings.json" />
        <EmbeddedResource Include="appsettings.Production.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <!-- This is in the .csproj file instead of a .cs file so that VS Code Cleanup cannot remove these before they are used -->
        <Using Include="System" />
        <Using Include="System.Collections.Generic" />
        <Using Include="System.Linq" />
        <Using Include="System.Threading.Tasks" />
        <Using Include="RevolutionaryStuff.Core" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\package\icon.png" Link="icon.png">
            <PackagePath>\package</PackagePath>
            <Pack>true</Pack>
        </None>
        <None Include="..\..\package\license.txt" Link="license.txt">
            <PackagePath>\package</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RevolutionaryStuff.Core\RevolutionaryStuff.Core.csproj" />
    </ItemGroup>

</Project>
