using System.Security.Cryptography;

namespace RevolutionaryStuff.Core.Crypto;

/// <summary>
/// Generates random values using a cryptographic random number generator.
/// </summary>
public static class Salt
{
    private static readonly RandomNumberGenerator RNG = RandomNumberGenerator.Create();

    /// <summary>
    /// Fills a byte array with cryptographically random bytes.
    /// </summary>
    /// <param name="buf">The array to fill.</param>
    public static void GetBytes(byte[] buf)
    {
        RNG.GetBytes(buf);
    }

    /// <summary>
    /// Gets a cryptographically random 32-bit signed integer.
    /// </summary>
    /// <value>A signed integer created from four cryptographically random bytes.</value>
    public static int RandomInteger
    {
        get
        {
            var data = new byte[4];
            GetBytes(data);
            return BitConverter.ToInt32(data, 0);
        }
    }

    /// <summary>
    /// Creates a GUID value from 16 cryptographically random bytes.
    /// </summary>
    /// <returns>A GUID created from newly generated random bytes.</returns>
    public static Guid CreateGuid()
    {
        return new Guid(CreateRandomBuf(16));
    }

    /// <summary>
    /// Creates a buffer of cryptographically random bytes with the specified length.
    /// </summary>
    /// <param name="Length">The number of bytes to generate.</param>
    /// <returns>A new buffer containing the generated bytes.</returns>
    public static byte[] CreateRandomBuf(uint Length)
    {
        var buf = new byte[Length];
        GetBytes(buf);
        return buf;
    }
}
